//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsWaterAt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsInfo
    {
        public int id { get; set; }
        public int idTicket { get; set; }
        public int idService { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Tickets Tickets { get; set; }
    }
}
